### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hamilyon** [qznc/dot#1]
Thank you for sharing your dotfiles!
Your comment from four years ago lead me here https://news.ycombinator.com/item?id=20999219

There is valuable code in this repo, can you please clarify the license situation?

**Comment by qznc** [comment]
I'm not sure if some of the config files should be considered derived, so I'm not sure if it makes sense to specify a license for the whole repo.

The relevant code (like git-overview) is only in the bin folder though, so I specified a license for everthing in there.
